# pytest.ini
[pytest]
; python_files = *.py
python_files = test_*.py

markers =
    smoke: Smoke test cases
    regression: Regression test cases
    positive: Positive test cases 
    negative: Negative test cases 
    login: All login-related tests
    forgot_password: Forgot password-related tests
    signup: All signup-related tests
    add_task: All add task-related tests
    special_add_task: All special task-related tests
    dashboard: All dashboard-related tests
    delete_task: All trash-related tests
    special_dashboard: All special dashboard-related tests
    normal_tp: All team performance dashboard-related tests
    special_tp: All special team performance dashboard-related tests
    notifications: All notifications-related tests
    compliance_history: All compliance history-related tests
    normal_task_sections: All task sections dashboard-related tests
    special_task_sections: All task sections dashboard-related tests
    updates: All updates-related tests
    project: All project-related tests
    settings: All settings-related tests
    overall_happy_path_flow: All overall_happy_path_flow-related tests
    notifications: All notification-related tests

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
